Fix test script to return failure status on exit
Fix test.sh script to return failure status on exit. Also, report final
status better.

diff --git a/test.sh.in b/test.sh.in
--- a/test.sh.in
+++ b/test.sh.in
@@ -217,8 +217,12 @@ rm -f test_temp_out.pluto.c
 rm -f test_temp_out.pluto.pluto.cloog
 }
 
-echo ===========================
+echo -ne "\n\n==========================="
 echo -e "$num_succ / $(($num_succ + $num_fail)) tests \e[32mPASSED\e[0m"
+if [ $num_fail -gt 0 ]; then
+	echo -e "$num_fail / $(($num_succ + $num_fail)) tests \e[31mFAILED\e[0m"
+fi
 echo ===========================
 
-trap cleanup SIGINT exit
+trap cleanup SIGINT exit $num_fail
+exit $num_fail
